//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ticket.Domain.SqlServer
{
    using System;
    using System.Collections.Generic;
    using ticket.DataAccess.Concrete;

    public partial class Ticket
    {
        public int Id { get; set; }
        public Nullable<int> AirplaneId { get; set; }
        public Nullable<int> FlightTypeId { get; set; }
        public Nullable<int> ScheduleId { get; set; }
    
        public virtual Airplane Airplane { get; set; }
        public virtual FlightType FlightType { get; set; }
        public virtual Schedule Schedule { get; set; }
        private ScheduleRepository scheduleRepositery= new ScheduleRepository();
        private AirplaneRepository airplaneRepository = new AirplaneRepository();
        public override string ToString()
        {
            var schedule = scheduleRepositery.GetData((int)ScheduleId);
            var airplane = airplaneRepository.GetData((int)AirplaneId);
            return $"{Airplane.Name} : {Airplane.Pilot.Name} - {Airplane.Pilot.Surname} - {Schedule.StartDateTime}";
        }
    }
}
